# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- FlowChart_Selection_Creation_Updation_Validation_Testing

pool:
  vmImage: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathPack@5
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'DevopsSCC'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Information'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'