# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UiPathPack@5
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    orchestratorConnection: 'DevopsSCC'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathTest@5
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'DevopsSCC'
    testSet: 'SAP_Testing_TestSet'
    folderName: 'RPAFolder'
- task: UiPathDeploy@5
  inputs:
    orchestratorConnection: 'DevopsSCC'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'RPAFolder'